<?php
/**
 * This class has been auto-generated by PHP-DI.
 */
class CompiledContainer extends DI\CompiledContainer{
    const METHOD_MAPPING = array (
  'appConfig' => 'get1',
  'dbConfig' => 'get2',
  'subEntry1' => 'get3',
  'Slim\\Views\\Twig' => 'get4',
  'App\\Views\\ExtensionTwig' => 'get5',
  'Slim\\Views\\TwigMiddleware' => 'get6',
  'PDO' => 'get7',
  'Doctrine\\DBAL\\Connection' => 'get8',
  'App\\Services\\QueryBuilderService' => 'get9',
  'App\\Core\\Controller' => 'get10',
  'App\\Core\\Model' => 'get11',
  'App\\Services\\Validators\\Validator' => 'get12',
  'App\\Interfaces\\UserRepositoryInterface' => 'get13',
  'App\\Services\\UserService' => 'get14',
  'App\\Models\\User' => 'get15',
  'App\\Controllers\\UserController' => 'get16',
  'App\\Services\\PasswordService' => 'get17',
  'App\\Interfaces\\RoleRepositoryInterface' => 'get18',
  'App\\Services\\RoleService' => 'get19',
  'App\\Models\\Role' => 'get20',
  'App\\Controllers\\RoleController' => 'get21',
  'App\\Interfaces\\AuthServiceInterface' => 'get22',
  'App\\Services\\AuthService' => 'get23',
  'Psr\\Log\\LoggerInterface' => 'get24',
  'App\\Controllers\\AuthController' => 'get25',
  'App\\Middlewares\\AuthMiddleware' => 'get26',
  'App\\Models\\RememberMe' => 'get27',
  'App\\Interfaces\\RememberMeRepositoryInterface' => 'get28',
  'App\\Services\\RememberMeService' => 'get29',
);

    protected function get1()
    {
        return [
            'debug' => false,
            'env' => 'production',
            'baseDir' => '/C:/wamp64/www/dashboard/app/cli',
            'url' => 'http://localhost/C:/wamp64/www/dashboard/app/cli',
            'current_route' => '/',
        ];
    }

    protected function get3()
    {
        return [
            3 => 2,
            19 => 2,
            20 => false,
            17 => false,
            1002 => 'SET NAMES utf8mb4',
        ];
    }

    protected function get2()
    {
        return [
            'driver' => 'mysql',
            'host' => 'localhost',
            'port' => '3306',
            'database' => 'dashboard',
            'username' => 'root',
            'password' => '',
            'charset' => 'utf8mb4',
            'options' => $this->get3(),
        ];
    }

    protected function get4()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): \Slim\Views\Twig {
        $appConfig = $c->get('appConfig');

        $twig = \Slim\Views\Twig::create('C:\\wamp64\\www\\dashboard\\app\\config' . "/../../templates/pages/", [
            'cache' => $appConfig['env'] === 'production'
                ? 'C:\\wamp64\\www\\dashboard\\app\\config' . '/../../storage/localcache'
                : false,
            'debug' => $appConfig['debug'],
            'auto_reload' => $appConfig['debug']
        ]);

        // Load menu itens
        $menu_items = require 'C:\\wamp64\\www\\dashboard\\app\\config' . '/../../templates/layout/components/config/menu-itens.php';

        // Global variables
        $twig->getEnvironment()->addGlobal('base_path', $appConfig['url']);
        $twig->getEnvironment()->addGlobal('get', $_GET ?? []);
        $twig->getEnvironment()->addGlobal('current_route', $appConfig['current_route']);
        $twig->getEnvironment()->addGlobal('menu_items', $menu_items);

        // Load external Twig functions
        $twig->addExtension($c->get(\App\Views\ExtensionTwig::class));

        if ($appConfig['env'] === 'development') {
            $twig->addExtension(new \Twig\Extension\DebugExtension());
            $twig->getEnvironment()->addGlobal('session', $_SESSION ?? []);
            $twig->getEnvironment()->addGlobal('cookies', $_COOKIE ?? []);
        }

        return $twig;
    }, 'Slim\\Views\\Twig');
    }

    protected function get5()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): \App\Views\ExtensionTwig {
        $appConfig = $c->get('appConfig');
        $routeParser = $c->get(\Slim\App::class)
            ->getRouteCollector()
            ->getRouteParser();
        return new \App\Views\ExtensionTwig(
            $routeParser,
            $appConfig['current_route'],
            $appConfig['baseDir']
        );
    }, 'App\\Views\\ExtensionTwig');
    }

    protected function get6()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return \Slim\Views\TwigMiddleware::createFromContainer($c->get(\Slim\App::class), \Slim\Views\Twig::class);
    }, 'Slim\\Views\\TwigMiddleware');
    }

    protected function get7()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        $dbConfig = $c->get('dbConfig');
        return \App\Core\Connection::getInstance($dbConfig);
    }, 'PDO');
    }

    protected function get8()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        $dbConfig = $c->get('dbConfig');
        $c->get(\PDO::class);

        // Configuration parameters of Doctrine DBAL
        $connectionParams = [
            'driver' => 'pdo_mysql',
            'host' => $dbConfig['host'],
            'port' => $dbConfig['port'],
            'dbname' => $dbConfig['database'],
            'user' => $dbConfig['username'],
            'password' => $dbConfig['password'],
            'charset' => $dbConfig['charset']
        ];

        return \Doctrine\DBAL\DriverManager::getConnection($connectionParams);
    }, 'Doctrine\\DBAL\\Connection');
    }

    protected function get9()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): \App\Services\QueryBuilderService {
        return new \App\Services\QueryBuilderService(
            $c->get(\Doctrine\DBAL\Connection::class)
        );
    }, 'App\\Services\\QueryBuilderService');
    }

    protected function get10()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): \App\Core\Controller {
        return new \App\Core\Controller(
            $c->get(\Slim\Views\Twig::class)
        );
    }, 'App\\Core\\Controller');
    }

    protected function get11()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): \App\Core\Model {
        return new \App\Core\Model(
            $c->get(\App\Services\QueryBuilderService::class)
        );
    }, 'App\\Core\\Model');
    }

    protected function get12()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): \App\Services\Validators\Validator {
        return new \App\Services\Validators\Validator($c);
    }, 'App\\Services\\Validators\\Validator');
    }

    protected function get13()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): \App\Interfaces\UserRepositoryInterface {
        return new \App\Models\User(
            $c->get(\App\Services\QueryBuilderService::class),
            $c->get(\App\Services\PasswordService::class)
        );
    }, 'App\\Interfaces\\UserRepositoryInterface');
    }

    protected function get14()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): \App\Services\UserService {
        return new \App\Services\UserService($c->get(\App\Interfaces\UserRepositoryInterface::class));
    }, 'App\\Services\\UserService');
    }

    protected function get15()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): \App\Models\User {
        return new \App\Models\User(
            $c->get(\App\Services\QueryBuilderService::class),
            $c->get(\App\Services\PasswordService::class)
        );
    }, 'App\\Models\\User');
    }

    protected function get16()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): \App\Controllers\UserController {
        return new \App\Controllers\UserController(
            $c->get(\Slim\Views\Twig::class),
            $c->get(\App\Services\UserService::class),
            $c->get(\App\Services\Validators\Validator::class),
            $c->get(\App\Models\Role::class)
        );
    }, 'App\\Controllers\\UserController');
    }

    protected function get17()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): \App\Services\PasswordService {
        return new \App\Services\PasswordService(12);
    }, 'App\\Services\\PasswordService');
    }

    protected function get18()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): \App\Interfaces\RoleRepositoryInterface {
        return new \App\Models\Role(
            $c->get(\App\Services\QueryBuilderService::class)
        );
    }, 'App\\Interfaces\\RoleRepositoryInterface');
    }

    protected function get19()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): \App\Services\RoleService {
        return new \App\Services\RoleService($c->get(\App\Interfaces\RoleRepositoryInterface::class));
    }, 'App\\Services\\RoleService');
    }

    protected function get20()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): \App\Models\Role {
        return new \App\Models\Role(
            $c->get(\App\Services\QueryBuilderService::class)
        );
    }, 'App\\Models\\Role');
    }

    protected function get21()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): \App\Controllers\RoleController {
        return new \App\Controllers\RoleController(
            $c->get(\Slim\Views\Twig::class),
            $c->get(\App\Services\RoleService::class),
            $c->get(\App\Services\Validators\Validator::class)
        );
    }, 'App\\Controllers\\RoleController');
    }

    protected function get22()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): \App\Interfaces\AuthServiceInterface {
        return new \App\Services\AuthService(
            $c->get(\App\Interfaces\UserRepositoryInterface::class),
            $c->get(\App\Interfaces\RememberMeRepositoryInterface::class)
        );
    }, 'App\\Interfaces\\AuthServiceInterface');
    }

    protected function get23()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): \App\Services\AuthService {
        return new \App\Services\AuthService(
            $c->get(\App\Interfaces\UserRepositoryInterface::class),
            $c->get(\App\Interfaces\RememberMeRepositoryInterface::class)
        );
    }, 'App\\Services\\AuthService');
    }

    protected function get24()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): \Psr\Log\LoggerInterface {
        $appConfig = $c->get('appConfig');
        $logger = new \Monolog\Logger('app');

        $logPath = 'C:\\wamp64\\www\\dashboard\\app\\config' . '/../../storage/logs/app.log';
        $handler = new \Monolog\Handler\StreamHandler($logPath, \Monolog\Logger::DEBUG);
        $logger->pushHandler($handler);

        return $logger;
    }, 'Psr\\Log\\LoggerInterface');
    }

    protected function get25()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): \App\Controllers\AuthController {
        return new \App\Controllers\AuthController(
            $c->get(\Slim\Views\Twig::class),
            $c->get(\App\Interfaces\AuthServiceInterface::class),
            $c->get(\Psr\Log\LoggerInterface::class),
            $c->get(\App\Services\Validators\Validator::class)
        );
    }, 'App\\Controllers\\AuthController');
    }

    protected function get26()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): \App\Middlewares\AuthMiddleware {
        return new \App\Middlewares\AuthMiddleware(
            $c->get(\App\Interfaces\AuthServiceInterface::class)
        );
    }, 'App\\Middlewares\\AuthMiddleware');
    }

    protected function get27()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): \App\Models\RememberMe {
        return new \App\Models\RememberMe(
            $c->get(\App\Services\QueryBuilderService::class),
        );
    }, 'App\\Models\\RememberMe');
    }

    protected function get28()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): \App\Models\RememberMe {
        return new \App\Models\RememberMe(
            $c->get(\App\Services\QueryBuilderService::class)
        );
    }, 'App\\Interfaces\\RememberMeRepositoryInterface');
    }

    protected function get29()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): \App\Services\RememberMeService {
        return new \App\Services\RememberMeService(
            $c->get(\App\Models\RememberMe::class)
        );
    }, 'App\\Services\\RememberMeService');
    }

}
