<?php
/**
 * This class has been auto-generated by PHP-DI.
 */
class CompiledContainer extends DI\CompiledContainer{
    const METHOD_MAPPING = array (
  'appConfig' => 'get1',
  'dbConfig' => 'get2',
  'subEntry1' => 'get3',
  'Slim\\Views\\Twig' => 'get4',
  'App\\Views\\ExtensionTwig' => 'get5',
  'Slim\\Views\\TwigMiddleware' => 'get6',
  'PDO' => 'get7',
  'Doctrine\\DBAL\\Connection' => 'get8',
  'App\\Services\\QueryBuilderService' => 'get9',
  'App\\Core\\Controller' => 'get10',
  'App\\Core\\Model' => 'get11',
  'App\\Services\\Validators\\Validator' => 'get12',
  'App\\Interfaces\\UserRepositoryInterface' => 'get13',
  'App\\Services\\UserService' => 'get14',
  'App\\Models\\User' => 'get15',
  'App\\Controllers\\UserController' => 'get16',
  'App\\Services\\PasswordService' => 'get17',
  'App\\Interfaces\\RoleRepositoryInterface' => 'get18',
  'App\\Services\\RoleService' => 'get19',
  'App\\Models\\Role' => 'get20',
  'App\\Controllers\\RoleController' => 'get21',
);

    protected function get1()
    {
        return [
            'debug' => false,
            'env' => 'production',
            'baseDir' => '/dashboard',
            'url' => 'http://localhost/dashboard',
            'current_route' => '/admin/users/19/edit',
        ];
    }

    protected function get3()
    {
        return [
            3 => 2,
            19 => 2,
            20 => false,
            17 => false,
            1002 => 'SET NAMES utf8mb4',
        ];
    }

    protected function get2()
    {
        return [
            'driver' => 'mysql',
            'host' => '127.0.0.1',
            'port' => '3306',
            'database' => 'dashboard',
            'username' => 'dashboard',
            'password' => 'dashboard',
            'charset' => 'utf8mb4',
            'options' => $this->get3(),
        ];
    }

    protected function get4()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): \Slim\Views\Twig {
        $appConfig = $c->get('appConfig');

        $twig = \Slim\Views\Twig::create('C:\\wamp64\\www\\dashboard\\app\\config' . "/../../templates/pages/", [
            'cache' => $appConfig['env'] === 'production'
                ? 'C:\\wamp64\\www\\dashboard\\app\\config' . '/../../storage/localcache'
                : false,
            'debug' => $appConfig['debug'],
            'auto_reload' => $appConfig['debug']
        ]);

        // Global variables
        $twig->getEnvironment()->addGlobal('base_path', $appConfig['url']);
        $twig->getEnvironment()->addGlobal('get', $_GET ?? []);
        $twig->getEnvironment()->addGlobal('current_route', $appConfig['current_route']);
        $twig->addExtension($c->get(\App\Views\ExtensionTwig::class));

        if ($appConfig['env'] === 'development') {
            $twig->addExtension(new \Twig\Extension\DebugExtension());
            $twig->getEnvironment()->addGlobal('session', $_SESSION ?? []);
        }

        return $twig;
    }, 'Slim\\Views\\Twig');
    }

    protected function get5()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): \App\Views\ExtensionTwig {
        $routeParser = $c->get(\Slim\App::class)
            ->getRouteCollector()
            ->getRouteParser();
        return new \App\Views\ExtensionTwig($routeParser);
    }, 'App\\Views\\ExtensionTwig');
    }

    protected function get6()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return \Slim\Views\TwigMiddleware::createFromContainer($c->get(\Slim\App::class), \Slim\Views\Twig::class);
    }, 'Slim\\Views\\TwigMiddleware');
    }

    protected function get7()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        $dbConfig = $c->get('dbConfig');
        return \App\Core\Connection::getInstance($dbConfig);
    }, 'PDO');
    }

    protected function get8()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        $dbConfig = $c->get('dbConfig');
        $c->get(\PDO::class);

        // Configuration parameters of Doctrine DBAL
        $connectionParams = [
            'driver' => 'pdo_mysql',
            'host' => $dbConfig['host'],
            'port' => $dbConfig['port'],
            'dbname' => $dbConfig['database'],
            'user' => $dbConfig['username'],
            'password' => $dbConfig['password'],
            'charset' => $dbConfig['charset']
        ];

        return \Doctrine\DBAL\DriverManager::getConnection($connectionParams);
    }, 'Doctrine\\DBAL\\Connection');
    }

    protected function get9()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): \App\Services\QueryBuilderService {
        return new \App\Services\QueryBuilderService(
            $c->get(\Doctrine\DBAL\Connection::class)
        );
    }, 'App\\Services\\QueryBuilderService');
    }

    protected function get10()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): \App\Core\Controller {
        return new \App\Core\Controller(
            $c->get(\Slim\Views\Twig::class)
        );
    }, 'App\\Core\\Controller');
    }

    protected function get11()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): \App\Core\Model {
        return new \App\Core\Model(
            $c->get(\App\Services\QueryBuilderService::class)
        );
    }, 'App\\Core\\Model');
    }

    protected function get12()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): \App\Services\Validators\Validator {
        return new \App\Services\Validators\Validator($c);
    }, 'App\\Services\\Validators\\Validator');
    }

    protected function get13()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): \App\Interfaces\UserRepositoryInterface {
        return new \App\Models\User(
            $c->get(\App\Services\QueryBuilderService::class),
            $c->get(\App\Services\PasswordService::class)
        );
    }, 'App\\Interfaces\\UserRepositoryInterface');
    }

    protected function get14()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): \App\Services\UserService {
        return new \App\Services\UserService($c->get(\App\Interfaces\UserRepositoryInterface::class));
    }, 'App\\Services\\UserService');
    }

    protected function get15()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): \App\Models\User {
        return new \App\Models\User(
            $c->get(\App\Services\QueryBuilderService::class),
            $c->get(\App\Services\PasswordService::class)
        );
    }, 'App\\Models\\User');
    }

    protected function get16()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): \App\Controllers\UserController {
        return new \App\Controllers\UserController(
            $c->get(\Slim\Views\Twig::class),
            $c->get(\App\Services\UserService::class),
            $c->get(\App\Services\Validators\Validator::class)
        );
    }, 'App\\Controllers\\UserController');
    }

    protected function get17()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): \App\Services\PasswordService {
        return new \App\Services\PasswordService(12);
    }, 'App\\Services\\PasswordService');
    }

    protected function get18()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): \App\Models\Role {
        return new \App\Models\Role(
            $c->get(\App\Services\QueryBuilderService::class)
        );
    }, 'App\\Interfaces\\RoleRepositoryInterface');
    }

    protected function get19()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): \App\Services\RoleService {
        return new \App\Services\RoleService($c->get(\App\Interfaces\RoleRepositoryInterface::class));
    }, 'App\\Services\\RoleService');
    }

    protected function get20()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): \App\Models\Role {
        return new \App\Models\Role(
            $c->get(\App\Services\QueryBuilderService::class)
        );
    }, 'App\\Models\\Role');
    }

    protected function get21()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): \App\Controllers\RoleController {
        return new \App\Controllers\RoleController(
            $c->get(\Slim\Views\Twig::class),
            $c->get(\App\Services\RoleService::class),
            $c->get(\App\Services\Validators\Validator::class)
        );
    }, 'App\\Controllers\\RoleController');
    }

}
