<?php
/**
 * This class has been auto-generated by PHP-DI.
 */
class CompiledContainer extends DI\CompiledContainer{
    const METHOD_MAPPING = array (
  'Psr\\Http\\Message\\ResponseFactoryInterface' => 'get1',
  'Slim\\Csrf\\Guard' => 'get2',
  'App\\Middlewares\\AuthMiddleware' => 'get3',
  'App\\Middlewares\\SetupMiddleware' => 'get4',
  'App\\Middlewares\\PermissionMiddleware' => 'get5',
  'http.middlewares' => 'get6',
  'App\\Controllers\\UserController' => 'get7',
  'App\\Controllers\\RoleController' => 'get8',
  'App\\Controllers\\AuthController' => 'get9',
  'App\\Controllers\\ForgotPasswordController' => 'get10',
  'App\\Controllers\\SetupController' => 'get11',
  'App\\Services\\QueryBuilderService' => 'get12',
  'App\\Services\\UserService' => 'get13',
  'App\\Services\\RoleService' => 'get14',
  'App\\Interfaces\\AuthServiceInterface' => 'get15',
  'App\\Interfaces\\ForgotPasswordServiceInterface' => 'get16',
  'App\\Services\\PasswordService' => 'get17',
  'Psr\\Log\\LoggerInterface' => 'get18',
  'PHPMailer\\PHPMailer\\PHPMailer' => 'get19',
  'App\\Services\\MailerService' => 'get20',
  'App\\Interfaces\\UserRepositoryInterface' => 'get21',
  'App\\Interfaces\\RoleRepositoryInterface' => 'get22',
  'App\\Interfaces\\RememberMeRepositoryInterface' => 'get23',
  'App\\Interfaces\\PermissionRepositoryInterface' => 'get24',
  'PDO' => 'get25',
  'Doctrine\\DBAL\\Connection' => 'get26',
  'Slim\\Views\\Twig' => 'get27',
  'App\\Views\\ExtensionTwig' => 'get28',
  'Slim\\Views\\TwigMiddleware' => 'get29',
  'appConfig' => 'get30',
  'dbConfig' => 'get31',
  'subEntry1' => 'get32',
  'smtpConfig' => 'get33',
);

    protected function get1()
    {
        return $this->resolveFactory(static fn() => new \Slim\Psr7\Factory\ResponseFactory(), 'Psr\\Http\\Message\\ResponseFactoryInterface');
    }

    protected function get2()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): \Slim\Csrf\Guard {

        $responseFactory = $c->get(\Slim\App::class)->getResponseFactory();
        $auth = $c->get(\App\Services\AuthService::class);
        $logger = $c->get(\Psr\Log\LoggerInterface::class);

        $guard = new \Slim\Csrf\Guard($responseFactory);
        $guard->setPersistentTokenMode(true);

        $guard->setFailureHandler(
            function (
                \Psr\Http\Message\ServerRequestInterface $request,
                \Psr\Http\Server\RequestHandlerInterface $handler
            ) use ($auth, $responseFactory, $logger) {

                $logger->warning('[CSRF] Token validation failed.', [
                    'method'      => $request->getMethod(),
                    'uri'         => \getRequestPath($request),
                    'had_session' => isset($_SESSION['user']),
                ]);

                if (!isset($_SESSION['user'])) {

                    if (isset($_SESSION['csrf'])) {
                        unset($_SESSION['csrf']);
                    }

                    \flash('error', \error('Formulário expirado. Recarregue a página e tente novamente.'));
                    return \redirect(\getRequestPath($request));
                }

                unset($_SESSION['csrf']);
                unset($_SESSION['user']);

                if (isset($_COOKIE['remember_me'])) {
                    \setcookie('remember_me', '', \time() - 3600, '/');
                    unset($_COOKIE['remember_me']);
                }

                \flash('error', \error('Sua sessão expirou. Tente novamente.'));
                return \redirect('/login');
            }
        );

        return $guard;
    }, 'Slim\\Csrf\\Guard');
    }

    protected function get3()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): \App\Middlewares\AuthMiddleware {
        return new \App\Middlewares\AuthMiddleware(
            $c->get(\App\Interfaces\AuthServiceInterface::class)
        );
    }, 'App\\Middlewares\\AuthMiddleware');
    }

    protected function get4()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): \App\Middlewares\SetupMiddleware {
        return new \App\Middlewares\SetupMiddleware(
            $c->get(\App\Interfaces\UserRepositoryInterface::class)
        );
    }, 'App\\Middlewares\\SetupMiddleware');
    }

    protected function get5()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): callable {

        return function (string $permission) use ($c): \App\Middlewares\PermissionMiddleware {

            return new \App\Middlewares\PermissionMiddleware(
                $c->get(\App\Interfaces\AuthServiceInterface::class),
                $permission
            );
        };
    }, 'App\\Middlewares\\PermissionMiddleware');
    }

    protected function get6()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): callable {

        return function (\Slim\App $app) use ($c) {

            // Body parsing
            $app->addBodyParsingMiddleware();

            // Method override
            $app->add(new \Slim\Middleware\MethodOverrideMiddleware());

            // Global Authentication middleware
            $app->add($c->get(\App\Middlewares\AuthMiddleware::class));

            return $app;
        };
    }, 'http.middlewares');
    }

    protected function get7()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): \App\Controllers\UserController {
        return new \App\Controllers\UserController(
            $c->get(\Slim\Views\Twig::class),
            $c->get(\App\Services\UserService::class),
            $c->get(\App\Services\Validators\Validator::class),
            $c->get(\App\Models\Role::class),
            $c->get(\Psr\Log\LoggerInterface::class)
        );
    }, 'App\\Controllers\\UserController');
    }

    protected function get8()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): \App\Controllers\RoleController {
        return new \App\Controllers\RoleController(
            $c->get(\Slim\Views\Twig::class),
            $c->get(\App\Services\RoleService::class),
            $c->get(\App\Services\Validators\Validator::class)
        );
    }, 'App\\Controllers\\RoleController');
    }

    protected function get9()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): \App\Controllers\AuthController {
        return new \App\Controllers\AuthController(
            $c->get(\Slim\Views\Twig::class),
            $c->get(\App\Interfaces\AuthServiceInterface::class),
            $c->get(\Psr\Log\LoggerInterface::class),
            $c->get(\App\Services\Validators\Validator::class)
        );
    }, 'App\\Controllers\\AuthController');
    }

    protected function get10()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): \App\Controllers\ForgotPasswordController {
        return new \App\Controllers\ForgotPasswordController(
            $c->get(\Slim\Views\Twig::class),
            $c->get(\App\Services\ForgotPasswordService::class),
            $c->get(\App\Services\Validators\Validator::class),
            $c->get(\Psr\Log\LoggerInterface::class)

        );
    }, 'App\\Controllers\\ForgotPasswordController');
    }

    protected function get11()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): \App\Controllers\SetupController {
        return new \App\Controllers\SetupController(
            $c->get(\Slim\Views\Twig::class),
            $c->get(\App\Services\UserService::class),
            $c->get(\App\Services\Validators\Validator::class),
            $c->get(\Psr\Log\LoggerInterface::class),
            $c->get(\App\Interfaces\AuthServiceInterface::class)
        );
    }, 'App\\Controllers\\SetupController');
    }

    protected function get12()
    {
        return $this->resolveFactory(static fn(\Psr\Container\ContainerInterface $c) => new \App\Services\QueryBuilderService(
        $c->get(\Doctrine\DBAL\Connection::class)
    ), 'App\\Services\\QueryBuilderService');
    }

    protected function get13()
    {
        return $this->resolveFactory(static fn(\Psr\Container\ContainerInterface $c) => new \App\Services\UserService(
        $c->get(\App\Interfaces\UserRepositoryInterface::class)
    ), 'App\\Services\\UserService');
    }

    protected function get14()
    {
        return $this->resolveFactory(static fn(\Psr\Container\ContainerInterface $c) => new \App\Services\RoleService(
        $c->get(\App\Interfaces\RoleRepositoryInterface::class)
    ), 'App\\Services\\RoleService');
    }

    protected function get15()
    {
        return $this->resolveFactory(static fn(\Psr\Container\ContainerInterface $c) => new \App\Services\AuthService(
        $c->get(\App\Interfaces\UserRepositoryInterface::class),
        $c->get(\App\Interfaces\RememberMeRepositoryInterface::class),
        $c->get(\App\Interfaces\PermissionRepositoryInterface::class)
    ), 'App\\Interfaces\\AuthServiceInterface');
    }

    protected function get16()
    {
        return $this->resolveFactory(static fn(\Psr\Container\ContainerInterface $c) => new \App\Services\ForgotPasswordService(
        $c->get(\App\Interfaces\UserRepositoryInterface::class),
        $c->get(\App\Services\MailerService::class),
        $c->get(\Psr\Log\LoggerInterface::class)
    ), 'App\\Interfaces\\ForgotPasswordServiceInterface');
    }

    protected function get17()
    {
        return $this->resolveFactory(static fn() => new \App\Services\PasswordService(12), 'App\\Services\\PasswordService');
    }

    protected function get18()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): \Psr\Log\LoggerInterface {
        $logger = new \Monolog\Logger('app');
        $logPath = 'C:\\wamp64\\www\\dashboard\\app\\config\\dependencies' . '/../../../storage/logs/app.log';
        $handler = new \Monolog\Handler\StreamHandler($logPath, \Monolog\Level::Debug);
        $logger->pushHandler($handler);
        return $logger;
    }, 'Psr\\Log\\LoggerInterface');
    }

    protected function get19()
    {
        return $this->resolveFactory(static function (): \PHPMailer\PHPMailer\PHPMailer {
        return new \PHPMailer\PHPMailer\PHPMailer(true);
    }, 'PHPMailer\\PHPMailer\\PHPMailer');
    }

    protected function get20()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): \App\Services\MailerService {

        $appConfig = $c->get('appConfig');

        return new \App\Services\MailerService(
            $c->get('smtpConfig'),
            $c->get(\Psr\Log\LoggerInterface::class),
            $c->get(\Slim\Views\Twig::class),
            $c->get(\PHPMailer\PHPMailer\PHPMailer::class),
            $appConfig['env'] === 'development'
        );
    }, 'App\\Services\\MailerService');
    }

    protected function get21()
    {
        return $this->resolveFactory(static fn(\Psr\Container\ContainerInterface $c) => new \App\Models\User(
        $c->get(\App\Services\QueryBuilderService::class),
        $c->get(\App\Services\PasswordService::class)
    ), 'App\\Interfaces\\UserRepositoryInterface');
    }

    protected function get22()
    {
        return $this->resolveFactory(static fn(\Psr\Container\ContainerInterface $c) => new \App\Models\Role(
        $c->get(\App\Services\QueryBuilderService::class)
    ), 'App\\Interfaces\\RoleRepositoryInterface');
    }

    protected function get23()
    {
        return $this->resolveFactory(static fn(\Psr\Container\ContainerInterface $c) => new \App\Models\RememberMe(
        $c->get(\App\Services\QueryBuilderService::class)
    ), 'App\\Interfaces\\RememberMeRepositoryInterface');
    }

    protected function get24()
    {
        return $this->resolveFactory(static fn(\Psr\Container\ContainerInterface $c) => new \App\Models\Permission(
        $c->get(\App\Services\QueryBuilderService::class)
    ), 'App\\Interfaces\\PermissionRepositoryInterface');
    }

    protected function get25()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        $dbConfig = $c->get('dbConfig');
        return \App\Core\Connection::getInstance($dbConfig);
    }, 'PDO');
    }

    protected function get26()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        $c->get(\PDO::class);
        $dbConfig = $c->get('dbConfig');

        $connectionParams = [
            'driver' => 'pdo_mysql',
            'host' => $dbConfig['host'],
            'port' => $dbConfig['port'],
            'dbname' => $dbConfig['database'],
            'user' => $dbConfig['username'],
            'password' => $dbConfig['password'],
            'charset' => $dbConfig['charset']
        ];

        return \Doctrine\DBAL\DriverManager::getConnection($connectionParams);
    }, 'Doctrine\\DBAL\\Connection');
    }

    protected function get27()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): \Slim\Views\Twig {
        $appConfig = $c->get('appConfig');

        $twig = \Slim\Views\Twig::create('C:\\wamp64\\www\\dashboard\\app\\config\\dependencies' . '/../../../templates/', [
            'cache' => $appConfig['env'] === 'production'
                ? \loader('/storage/localcache')
                : false,
            'debug' => $appConfig['debug'],
            'auto_reload' => $appConfig['debug']
        ]);

        $menu_items = \loader('/templates/layout/components/config/menu-itens.php');

        $twig->getEnvironment()->addGlobal('base_path', $appConfig['url']);
        $twig->getEnvironment()->addGlobal('get', $_GET ?? []);
        $twig->getEnvironment()->addGlobal('current_route', $appConfig['current_route']);
        $twig->getEnvironment()->addGlobal('menu_items', $menu_items);

        $twig->addExtension($c->get(\App\Views\ExtensionTwig::class));

        if ($appConfig['env'] === 'development') {
            $twig->addExtension(new \Twig\Extension\DebugExtension());
            $twig->getEnvironment()->addGlobal('session', $_SESSION ?? []);
            $twig->getEnvironment()->addGlobal('cookies', $_COOKIE ?? []);
        }

        return $twig;
    }, 'Slim\\Views\\Twig');
    }

    protected function get28()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): \App\Views\ExtensionTwig {
        $appConfig = $c->get('appConfig');

        /** @var App $app */
        $app = $c->get(\Slim\App::class);

        $routeParser = $app->getRouteCollector()->getRouteParser();

        return new \App\Views\ExtensionTwig(
            $routeParser,
            $c->get(\Slim\Csrf\Guard::class),
            $appConfig['current_route'],
            $appConfig['baseDir']
        );
    }, 'App\\Views\\ExtensionTwig');
    }

    protected function get29()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return \Slim\Views\TwigMiddleware::createFromContainer(
            $c->get(\Slim\App::class),
            \Slim\Views\Twig::class
        );
    }, 'Slim\\Views\\TwigMiddleware');
    }

    protected function get30()
    {
        return [
            'debug' => false,
            'env' => 'production',
            'baseDir' => '/dashboard',
            'url' => 'http://localhost/dashboard',
            'current_route' => '/admin/roles',
        ];
    }

    protected function get32()
    {
        return [
            3 => 2,
            19 => 2,
            20 => false,
            17 => false,
            1002 => 'SET NAMES utf8mb4',
        ];
    }

    protected function get31()
    {
        return [
            'driver' => 'mysql',
            'host' => 'localhost',
            'port' => '3306',
            'database' => 'dashboard',
            'username' => 'root',
            'password' => '',
            'charset' => 'utf8mb4',
            'options' => $this->get32(),
        ];
    }

    protected function get33()
    {
        return [
            'host' => NULL,
            'port' => 0,
            'auth' => false,
            'username' => NULL,
            'password' => '',
            'encryption' => 'tls',
            'from_email' => NULL,
            'from_name' => '',
        ];
    }

}
